version: '3.2'

services:
    ms:
        image: corfr/leshan
        ports:
        - 8080:8080/tcp
        - 5683:5683/udp
        depends_on:
        - bss
    bss:
        image: corfr/leshan
        ports:
        - 8081:8080
        command: bootstrap
    weather:
        image: alliasd/eliot
        command: ${WEATHER}
        depends_on:
        - bss
        - ms
    presence:
        image: alliasd/eliot
        command: ${PRESENCE}
        depends_on:
        - bss
        - ms
    radiator:
       image: alliasd/eliot
       command: ${RADIATOR}
       depends_on:
       - bss
       - ms
    light:
       image: alliasd/eliot
       command: ${LIGHT}
       depends_on:
       - bss
       - ms
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      expose:
      - 9090 # Expose port to liked services
      ports:
      - 9090:9090
      command:
      - --config.file=/etc/prometheus/prometheus.yml
      volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      depends_on: # Wait for other services to come up (not esplicitly necessary)
      - cadvisor
      - node-exporter
      links: 
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    cadvisor:
      image: google/cadvisor:latest
      container_name: cadvisor
      ports:
      - 10000:8080
      volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      depends_on:
      - bss
      - ms
    node-exporter:
      image: prom/node-exporter:latest
      container_name: monitoring_node_exporter
      restart: unless-stopped
      expose:
        - 9100 # Only accessible to linked services
    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
      - 3000:3000
      depends_on:
      - prometheus
      links:
      - prometheus:prometheus



