version: '3.2'

services:
    ms:
        image: corfr/leshan
        ports:
        - 8080:8080/tcp
        - 5683:5683/udp
        depends_on:
        - bss
    bss:
        image: corfr/leshan
        ports:
        - 8081:8080
        command: bootstrap
    weather:
        image: alliasd/eliot
        command: ${WEATHER}
        depends_on:
        - bss
        - ms
    presence:
        image: alliasd/eliot
        command: ${PRESENCE}
        depends_on:
        - bss
        - ms
    radiator:
       image: alliasd/eliot
       command: ${RADIATOR}
       depends_on:
       - bss
       - ms
    light:
       image: alliasd/eliot
       command: ${LIGHT}
       depends_on:
       - bss
       - ms
