scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - 'cadvisor:8080'
    - 'cadvisor:10000'
- job_name: node-exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - 'node-exporter:9100'

