{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": "label_values(container_group)" },
   { "name": "interval", "label": "Interval", "query": "5s, 15s, 30s,1m,2m,3m,5m" },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Time since the first K8s service started (usually kubernetes-apiservers).",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - min(process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Activation time",
   "type": "singlestat",
   "description": "Time from the creation of the first ELIoT pod to the time the last ELIoT pod started.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "- min(kube_pod_created{namespace=\"eliot\"}) + max(kube_pod_start_time{namespace=\"eliot\"})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "description": "Count all the running containers (excluding ELIoT).",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kube_pod_info)" }
   ]
  },
  {
   "title": "Eliot Containers",
   "type": "singlestat",
   "description": "Count the Eliot containers currently running.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"eliot\"})"
    }
   ]
  },
  {
   "title": "Disk space used",
   "type": "singlestat",
   "description": "Disk space used on the K8s node.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{kubernetes_namespace=\"monitoring\"} - node_filesystem_avail_bytes{kubernetes_namespace=\"monitoring\"} )/ node_filesystem_size_bytes{kubernetes_namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "description": "Memory used on the selected node.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "description": "Average system load per node calculated every minute.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "avg(node_load1)" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Throughput of ELIoT clients.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"eliot\",pod!~\"eliot-server-.*\",pod!~\"eliot-bootstrap-server-.*\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage from ELIoT containers",
   "type": "graph",
   "description": "Average CPU usage from ELIoT containers.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{namespace=\"eliot\"}[$interval]))",
     "legendFormat": "nur container"
    }
   ]
  },
  {
   "title": "CPU Usage from other containers",
   "type": "graph",
   "description": "CPU usage from containers different than ELIoT containers.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{namespace!=\"eliot\"}[$interval]))",
     "legendFormat": "nur container"
    }
   ]
  },
  {
   "title": " ELIot containers Received Network Traffic",
   "type": "graph",
   "description": "Network traffic that is received by ELIoT containers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"eliot\"}[$interval])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic from other containers",
   "type": "graph",
   "description": "Network traffic that is received by other containers.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_network_receive_bytes_total{namespace!=\"eliot\"}[$interval])) by (pod),\"pod\", \"other\",\"pod\",\"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per ELIot containers",
   "type": "graph",
   "description": "Network traffic that is sent by ELIoT containers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"eliot\"}[$interval])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per other Containers",
   "type": "graph",
   "description": "Network traffic that is sent by other containers.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_network_transmit_bytes_total{namespace!=\"eliot\"}[$interval])) by (pod),\"pod\", \"other\",\"pod\",\"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per ELIot containers",
   "type": "graph",
   "description": "Cumulative CPU time consumed for the ELIoT containers from the beginning of the test.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=\"eliot\"}) by (pod) / scalar(sum(node_cpu_seconds_total))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage from other containers",
   "type": "graph",
   "description": "Cumulative CPU time consumed for containers different than the ELIoT containers.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(container_cpu_usage_seconds_total{namespace!=\"eliot\",pod=~\".+\"}) by (pod) / scalar(sum(node_cpu_seconds_total)), \"pod\", \"other\",\"pod\",\"\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage per ELIot containers",
   "type": "graph",
   "description": "Memory consumed by ELIoT containers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"eliot\"}) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per other Containers",
   "type": "graph",
   "description": "Memory consumed by other containers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_usage_bytes{namespace!=\"eliot\", pod=~\".+\"}) by (pod),\"pod\", \"other\",\"pod\",\"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container startup time",
   "type": "bargauge",
   "description": "Startup time of each ELIoT container in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"Value\",- sort(kube_pod_created{namespace=\"eliot\"}) + kube_pod_start_time{namespace=\"eliot\"})",
     "legendFormat": "{{Value}}s"
    }
   ]
  }
 ]
}