{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": "label_values(container_group)" },
   { "name": "interval", "label": "Interval", "query": "5s, 15s, 30s,1m,2m,3m,5m" },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{namespace=\"eliot\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{namespace=\"eliot\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{kubernetes_namespace=\"monitoring\"} - node_filesystem_avail_bytes{kubernetes_namespace=\"monitoring\"} )/ node_filesystem_size_bytes{kubernetes_namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{kubernetes_namespace=\"monitoring\"} - node_memory_SwapFree_bytes{kubernetes_namespace=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_load1{kubernetes_namespace=\"monitoring\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{kubernetes_namespace=\"monitoring\"}))"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage from ELIoT containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{namespace=\"eliot\"}[1m]))",
     "legendFormat": "nur container"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$server:.*\"}))"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{fstype=\"aufs\"} - node_filesystem_free{fstype=\"aufs\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal - node_memory_MemAvailable",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_disk_bytes_read[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic from ELIot containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"eliot\"}[$interval])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic from other containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace!=\"eliot\"}[$interval])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per ELIot containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"eliot\"}[$interval])) by (pod) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage from other containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!=\"eliot\"}[$interval])) by (pod) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per ELIot containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"eliot\"}) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per other Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace!=\"eliot\"}) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per ELIot containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"eliot\"}[$interval])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per other Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace!=\"eliot\"}[$interval])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per ELIot Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{namespace=\"eliot\"}) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per other Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{namespace!=\"eliot\"}) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\".+\"} - container_memory_usage_bytes{name=~\".+\"})  * 100 / container_spec_memory_limit_bytes{name=~\".+\"}) ) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\"}) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}