kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000 #Prometheus
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001 #Grafana
    hostPort: 30001
    protocol: TCP
  - containerPort: 30002 #Leshan Server
    hostPort: 30002
    protocol: TCP
  - containerPort: 30003 #Leshan Bootstrap Server
    hostPort: 30003
    protocol: TCP
  extraMounts:
  - hostPath: /tmp/eliot
    containerPath: /tmp/eliot
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
