apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      nodeName: "kind-control-plane"
      containers:
      - name: grafana
        image: grafana/grafana:7.1.3
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      securityContext:
        runAsUser: 0 # Needed to access kind folders
      volumes:
        - name: grafana-storage
          hostPath:
              path: /tmp/eliot/grafana-storage
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
