apiVersion: v1
kind: Service
metadata:
  name: eliot-server
  namespace: eliot
  annotations:
      prometheus.io/scrape: 'false'
spec:
  selector:
    app: eliot-server
  type: NodePort
  ports:
    - name: gui
      port: 8080
      targetPort: 8080
      nodePort: 30002
    - name: coap
      protocol: UDP
      port: 5683
      targetPort: 5683
